defaults: &defaults
  docker:
  - image: circleci/golang:1.12

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Build Docker container
          command: docker build -t navikt/mutatingflow:latest .
      - run:
          name: Save Docker container
          command: docker save navikt/mutatingflow:latest -o /tmp/workspace/docker-image.tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker-image.tar
  release:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "13:72:55:e3:07:7c:c7:7e:d6:cd:a2:2f:d2:8e:cb:b5"
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker container
          command: docker load -i /tmp/workspace/docker-image.tar
      - run:
          name: Login to Dockerhub
          command: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run:
          name: Push Docker container
          command: |
            version=$(./version.sh)
            docker tag navikt/mutatingflow:latest navikt/mutatingflow:${version}
            docker push navikt/mutatingflow:latest
            docker push navikt/mutatingflow:${version}
      - run:
          name: Deploy new version to Kubernetes
          command: |
            version=$(./version.sh)
            naisyaml=$(mktemp -d)
            git clone git@github.com:navikt/nais-yaml $naisyaml
            cd $naisyaml
            sed -E -i "s#image: navikt/mutatingflow:.+#image: navikt/mutatingflow:${version}#" vars/mutatingflow.yaml
            git add .
            git --no-pager diff --cached
            git commit -a -m "Bump Mutatingflow to version ${version}"
            git push
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          context: NAIS deployment
          requires:
            - build
          filters:
            branches:
              only: master
