---
apiVersion: v1
kind: Service
metadata:
  name: mutatingflow
  labels:
    app: mutatingflow
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: mutatingflow
  type: ClusterIP
