// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	notebook_v1alpha1 "github.com/navikt/mutatingflow/pkg/apis/notebook/v1alpha1"
	versioned "github.com/navikt/mutatingflow/pkg/client/clientset/versioned"
	internalinterfaces "github.com/navikt/mutatingflow/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/navikt/mutatingflow/pkg/client/listers/notebook/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NotebookInformer provides access to a shared informer and lister for
// Notebooks.
type NotebookInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NotebookLister
}

type notebookInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNotebookInformer constructs a new informer for Notebook type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNotebookInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNotebookInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNotebookInformer constructs a new informer for Notebook type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNotebookInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NotebookV1alpha1().Notebooks(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NotebookV1alpha1().Notebooks(namespace).Watch(options)
			},
		},
		&notebook_v1alpha1.Notebook{},
		resyncPeriod,
		indexers,
	)
}

func (f *notebookInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNotebookInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *notebookInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&notebook_v1alpha1.Notebook{}, f.defaultInformer)
}

func (f *notebookInformer) Lister() v1alpha1.NotebookLister {
	return v1alpha1.NewNotebookLister(f.Informer().GetIndexer())
}
