// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NotebookListerExpansion allows custom methods to be added to
// NotebookLister.
type NotebookListerExpansion interface{}

// NotebookNamespaceListerExpansion allows custom methods to be added to
// NotebookNamespaceLister.
type NotebookNamespaceListerExpansion interface{}
